chore: use hasura ce image
SocialGouv/carnet-de-bord pull request #1113
Opened 2022-09-26 07:14 UTC by lionelB

## :wrench: Problème

L'image docker d'hasura utilisé actuellement contient à la fois les composant open source et closed source et est en retard de version. 
Depuis la version 2.12, Hasura met à disposition une image avec seulement les composants opensource. Cela permettrait d'alléger l'image finale. Afin de pouvoir bénéficier des dernieres fonctionnalité ainsi que les corrections de bug,  on souhaite avoir des mises à jour régulière.

## :cake: Solution

mettre à jour le nom de l'image utilisée avec le prefix `-ce`  

## :desert_island: Comment tester

Si tests e2e passent on peut être confiant dans le bon fonctionnement de l'appli

Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).

2022-09-26 07:49 UTC, vjousse approved these changes
Testé en local sur mon Archlinux, fonctionne parfaitement :+1:

2022-09-26 08:00 UTC, jonathanperret commented
Plus précisément c'est depuis la 2.12 qu'ils mettent les composants payants dans l'image par défaut "pour simplifier les upgrades" 😏 .
Je regarde pourquoi le déploiement de RA sur Scalingo a échoué.

2022-09-26 10:04 UTC, jonathanperret requested changes
Malheureusement il y a plusieurs autres endroits où la version de Hasura est mentionnée et donc à mettre à jour :
- https://github.com/SocialGouv/carnet-de-bord/blob/0997e65dd3f31203a65c0ea6a0f5f493f4eda81f/.github/workflows/test.yml#L28
- https://github.com/SocialGouv/carnet-de-bord/blob/0997e65dd3f31203a65c0ea6a0f5f493f4eda81f/.github/workflows/test.yml#L72
- https://github.com/SocialGouv/carnet-de-bord/blob/0997e65dd3f31203a65c0ea6a0f5f493f4eda81f/.github/workflows/test.yml#L121
- https://github.com/SocialGouv/carnet-de-bord/blob/0997e65dd3f31203a65c0ea6a0f5f493f4eda81f/INSTALL.md?plain=1#L10
- https://github.com/SocialGouv/carnet-de-bord/blob/0997e65dd3f31203a65c0ea6a0f5f493f4eda81f/package.json#L66
- https://github.com/SocialGouv/carnet-de-bord/blob/0997e65dd3f31203a65c0ea6a0f5f493f4eda81f/yarn.lock#L4745
- la configuration des applications Scalingo (variables d'environnement).

Il y a sûrement quelques pistes pour éviter de répéter cette version, par exemple :
- l'enlever dans `INSTALL.md`,
- fixer le numéro dans l'action locale d'installation de Hasura CLI au lieu d'en faire un paramètre https://github.com/SocialGouv/carnet-de-bord/blob/0997e65dd3f31203a65c0ea6a0f5f493f4eda81f/.github/actions/hasura-cli/action.yml#L1-L18 
- peut-être qu'on n'a pas besoin de la dépendance à `hasura-cli` qui est dans le `package.json` + `yarn.lock` ?
- pour éviter l'adhérence à une variable d'environnement Scalingo, on pourrait modifier le [_buildpack_ Hasura](https://github.com/jonathanperret/scalingo-hasura-buildpack) pour qu'il respecte par exemple un fichier `.hasura-version` à la racine.

Après ce n'est pas forcément très critique si on ne change pas de version tous les 2 jours ?

2022-09-26 17:56 UTC, lionelB commented
effectivement je suis allé un peu vite
Pour le package.json je l'ai viré dans une pr mais je la retrouve pas). il faudra modifier les commandes hasura des readme.
je vais faire un premier passage :)

2022-09-28 13:45 UTC, jonathanperret commented on .github/actions/hasura-cli/action.yml
> +    description: "Hasura version"
L'exemple de numéro de version était là pour préciser la syntaxe (avec ou sans le `v`…) parce que je ne m'en souvenais jamais 😅

2022-09-29 07:12 UTC, lionelB commented on .github/actions/hasura-cli/action.yml
> +    description: "Hasura version"
```suggestion
    description: "Hasura version (without leading v)"
```

2022-09-29 08:13 UTC, merged