fix(frontend): remove username from user creation form
SocialGouv/carnet-de-bord pull request #247
Opened 2021-09-23 11:50 UTC by lionelB

move username field form AccountRequest to Account (thx @Augustin82 )

2021-09-23 13:02 UTC, Augustin82 requested changes

2021-09-23 13:02 UTC, Augustin82 commented on src/routes/inscription/request.ts
> +	username += `${account.length + 1}`;
Et d'ailleurs, account.length sera toujours 0 ou 1.
Ce que j'avais en tête, c'était de faire une boucle pour ajouter 1, 2, 3, etc. jusqu'à ce qu'on tombe sur un login unique.
Par exemple, si l'email c'est augustin@truc.fr, on essaie augustin, puis augustin1, puis augustin2, etc.

2021-09-23 15:50 UTC, lionelB commented on src/routes/inscription/request.ts
> +	username += `${account.length + 1}`;
Pour simplifier, j'étais parti pour faire login + chiffre mais je peux faire login pour le premier et si y'a un doublon ca donnerait 
- login
- login1
- login2,...

2021-09-23 16:24 UTC, lionelB commented on src/routes/inscription/request.ts
> +	username += `${account.length + 1}`;
du coup j'ai changé, :)

2021-09-24 07:01 UTC, Augustin82 approved these changes

2021-09-24 07:05 UTC, merged