feat: add admin home
SocialGouv/carnet-de-bord pull request #370
Opened 2021-10-31 15:38 UTC by lionelB

- create a deployment (and basic admin stat)

2021-10-31 21:16 UTC, Augustin82 requested changes

2021-10-31 21:16 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentCreateLayer.svelte
> +		console.log('submit');
nitpick : remove this?

2021-10-31 21:16 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentCreateLayer.svelte
> +	import { Input } from '../base';
nitpick : use $lib alias?

2021-10-31 21:16 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentCreateLayer.svelte
> +	import Button from '../base/Button.svelte';
nitpick : use $lib alias?

2021-10-31 21:16 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentDetail.svelte
> +<p>Référent: {deployment?.managers.map((item) => displayFullName(item)).join(', ')}</p>
nitpick : use non-breaking space before the ":"?

2021-10-31 21:16 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentDetail.svelte
> +	Déploiement <span class="text-france-blue-500">{deployment?.label}</span>
nitpick : use \<Text\> to handle null

2021-10-31 21:16 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentList.svelte
> +	import { displayFullName } from '../format';
nitpick : use $lib alias

2021-10-31 21:16 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentList.svelte
> +	import LoaderIndicator from '../utils/LoaderIndicator.svelte';
nitpick : use $lib alias

2021-10-31 21:16 UTC, Augustin82 commented on src/routes/admin/__layout.svelte
> +<script type="ts">
issue : this should be "lang", right?

2021-10-31 21:16 UTC, Augustin82 commented on src/routes/admin/__layout.svelte
> +<script type="ts" context="module">
issue : this should be "lang", right?

2021-10-31 21:16 UTC, Augustin82 commented on src/routes/admin/deployment/[uuid].svelte
> +	<title>Deploiment {deployment?.label} - carnet de bord</title>
issue : Deploiment => Déploiement
nitpick : carnet de bord => Carnet de bord
nitpick : use <Text> to handle null

2021-10-31 21:16 UTC, Augustin82 commented on src/routes/admin/index.svelte
> +	<title>Gestion des déploiements - carnet de bord</title>
nitpick : carnet de bord => Carnet de bord

2021-10-31 21:16 UTC, Augustin82 commented on src/routes/manager/index.svelte
> +yo
issue : what should go there?

2021-11-02 08:01 UTC, lionelB commented on src/routes/admin/__layout.svelte
> +<script type="ts">
yup -_-'

2021-11-02 08:02 UTC, lionelB commented on src/routes/manager/index.svelte
> +yo
nothing it was a test :)

2021-11-02 20:21 UTC, Augustin82 commented on src/lib/ui/AdminDeployment/AdminDeploymentDetail.svelte
> +<p>Référent&nbs: {deployment?.managers.map((item) => displayFullName(item)).join(', ')}</p>
issue : `&nbsp;`

2021-11-02 20:21 UTC, Augustin82 commented on src/routes/admin/deployment/[uuid].svelte
> +	<title>Deploiement {deployment?.label ?? ''} - Carnet de bord</title>
nitpick : Déploiement

2021-11-04 08:31 UTC, Augustin82 approved these changes

2021-11-04 08:49 UTC, merged