feat: remove structure_sollicitées from notebook_actions
SocialGouv/carnet-de-bord pull request #390
Opened 2021-11-15 13:12 UTC by lionelB

- remove structures sollicitées 
  - migration
  - remove ui

2021-11-15 14:57 UTC, Augustin82 requested changes

2021-11-15 14:57 UTC, Augustin82 commented on src/lib/graphql/_gen/typed-document-nodes.ts
> +	config?: Maybe<Scalars['jsonb']>;
Ça devrait pas être dans un autre commit, ça ?

2021-11-15 16:14 UTC, lionelB commented on src/lib/graphql/_gen/typed-document-nodes.ts
> +	config?: Maybe<Scalars['jsonb']>;
bizarre que ce soit la meme :/

2021-11-16 09:58 UTC, Augustin82 approved these changes

2021-11-16 10:20 UTC, merged