Feat/add more manager
SocialGouv/carnet-de-bord pull request #913
Opened 2022-07-04 19:48 UTC by lionelB

fix #863

2022-07-05 03:44 UTC, vjousse requested changes

2022-07-05 03:44 UTC, vjousse commented on backend/api/core/emails.py
>      username: str, firstname: str | None, lastname: str | None, access_key: str
`access_key` devrait être de type `UUID` ici non ?

2022-07-05 03:44 UTC, vjousse commented on backend/api/db/crud/admin_pdi.py
> +    )
```suggestion
    return AdminPdi.parse_obj(record)
```

2022-07-05 03:44 UTC, vjousse commented on backend/api/db/crud/admin_pdi.py
> +            INSERT INTO public.manager(deployment_id, email, firstname, lastname)
Puisque l'on gère des `manager` est-ce que le fichier ne devrait pas plutôt s'appeler `manager.py` au lieu d'`admin_pdi.py` histoire de rester cohérent ?

2022-07-05 03:44 UTC, vjousse commented on backend/api/db/models/admin_pdi.py
> +class AdminPdiInput(BaseModel):
Idem, pourquoi ne pas utiliser `Manager` dans ce fichier ?

2022-07-05 03:44 UTC, vjousse commented on backend/api/v1/routers/admins.py
> +FORMAT = "[%(asctime)s:%(filename)s:%(lineno)s - %(funcName)20s() ] %(message)s"
Ça faut qu'on se sorte dans les settings, c'est dupliqué un peu partout là.

2022-07-05 03:44 UTC, vjousse commented on backend/api/v1/routers/admins.py
> +from datetime import datetime
Non utilisé ?

2022-07-05 03:44 UTC, vjousse commented on backend/api/v1/routers/admins.py
> +from asyncpg.connection import Connection
Non utilisé ?

2022-07-05 03:44 UTC, vjousse commented on backend/api/v1/routers/admins.py
> +from fastapi import APIRouter, BackgroundTasks, Depends, Request
`Request` semble non utilisé ?

2022-07-05 03:44 UTC, vjousse commented on backend/api/v1/routers/admins.py
> +        admin_pdi = await insert_admin_pdi(connection=db, data=admin)
Attention, ici le tye de `admin_pdi` est `AdminPDI | None`, il faut gérer le `None`

2022-07-05 03:44 UTC, vjousse commented on backend/api/v1/routers/admins.py
> +                access_key=account.access_key,
Idem `account` peut être `None`, il faut le gérer.

2022-07-05 03:44 UTC, vjousse commented on backend/api/v1/dependencies.py
> +    )
Je sais que tu sais, mais on a un beau code smell ici :-)

Il serait préférable à mon avis d'utiliser des dépendances paramétrées : https://fastapi.tiangolo.com/advanced/advanced-dependencies/

2022-07-05 03:44 UTC, vjousse commented on backend/tests/api/test_admins.py
> +    )
Je pense que ça vaut le coup de rajouter la fonction dans le crud, ça coûte pas grand chose et pourra être utile pas la suite.

2022-07-05 03:44 UTC, vjousse commented on backend/tests/conftest.py
> +    return "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwczovL2hhc3VyYS5pby9qd3QvY2xhaW1zIjp7IngtaGFzdXJhLWFsbG93ZWQtcm9sZXMiOlsiYWRtaW5fY2RiIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6ImFkbWluX2NkYiIsIngtaG
Est-ce que tu pourrais peut-être juste rajouter un commentaire pour dire comment tu les as généré si c'est pas trop compliqué ?

2022-07-05 07:06 UTC, lionelB commented on backend/api/core/emails.py
>      username: str, firstname: str | None, lastname: str | None, access_key: str
C’est un string dans la base

2022-07-05 16:19 UTC, lionelB commented on backend/api/v1/dependencies.py
> +    )
j'ai pas regardé cette partie. je veux bien qu'on regarde ensemble :)

2022-07-07 11:54 UTC, vjousse approved these changes

2022-07-07 15:02 UTC, merged